name: 'Despliegue Automático ITAM'

# El robot se despierta cada vez que alguien hace "push" a la rama main
on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga tu código desde GitHub
    - name: Checkout del Repositorio
      uses: actions/checkout@v3

    # 2. Instala Terraform en el servidor de GitHub
    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@v2

    # 3. Se autentica en Google Cloud usando el secreto
    - name: Autenticación en Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # 4. LA MAGIA: Reconstruye los archivos secretos de forma SEGURA
    - name: Inyectar Secretos
      env:
        SECRET_TF: ${{ secrets.TF_VARS }}
        SECRET_AZURE: ${{ secrets.AZURE_CONFIG }}
        SECRET_GCP: ${{ secrets.GCP_CONFIG }}
        SECRET_HUAWEI: ${{ secrets.HUAWEI_CONFIG }}
      run: |
        echo "$SECRET_TF" > prueba-terraform-gcp/secretos.auto.tfvars
        echo "$SECRET_AZURE" > extractor-azure/config.json
        echo "$SECRET_GCP" > extractor-gcp/config.json
        echo "$SECRET_HUAWEI" > extractor-huawei/config.json

    # 5. Conecta Terraform a tu Bucket de Estado (El Cerebro)
    - name: Terraform Init
      run: terraform init
      working-directory: ./prueba-terraform-gcp

    # 6. Aplica los cambios automáticamente en Google Cloud
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./prueba-terraform-gcp
